// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cmc.remt.svr;

import com.cmc.remt.domain.HouseInfo;
import com.cmc.remt.repo.GlobalSearch;
import com.cmc.remt.svr.HouseInfoSvr;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HouseInfoSvr_Roo_Service {
    
    @Transactional(readOnly = false)
    public abstract HouseInfo HouseInfoSvr.save(HouseInfo entity);    
    @Transactional(readOnly = false)
    public abstract void HouseInfoSvr.delete(Long id);    
    @Transactional(readOnly = false)
    public abstract List<HouseInfo> HouseInfoSvr.save(Iterable<HouseInfo> entities);    
    @Transactional(readOnly = false)
    public abstract void HouseInfoSvr.delete(Iterable<Long> ids);    
    public abstract List<HouseInfo> HouseInfoSvr.findAll();    
    public abstract List<HouseInfo> HouseInfoSvr.findAll(Iterable<Long> ids);    
    public abstract HouseInfo HouseInfoSvr.findOne(Long id);    
    public abstract long HouseInfoSvr.count();    
    public abstract Page<HouseInfo> HouseInfoSvr.findAll(GlobalSearch globalSearch, Pageable pageable);    
}
